# Common Settings
## Spring Actuator Setting
### TODO: to grant access to the public. THIS SHOULD BE REMOVED BEFORE PRODUCTION DEPLOYMENT.
management:
  security:
    enabled: false

spring:
  ## Thymeleaf 3
  thymeleaf:
    # TODO: Currently(~3.0.7) Thymeleaf Decoupled logic cannot be tested via Spring MockMvc, so abandon this feature. 
    decoupled-logic: false
