# Common Settings
## Spring Actuator Setting
### TODO: to grant access to the public. THIS SHOULD BE REMOVED BEFORE PRODUCTION DEPLOYMENT.
management:
  security:
    enabled: false

## Logging
logging:
  level: { com: DEBUG }

## Spring properties
spring:
  ## Thymeleaf 3
  thymeleaf:
    decoupled-logic: true
