# Common Settings
## Spring Actuator Setting
### TODO: to grant access to the public. THIS SHOULD BE REMOVED BEFORE PRODUCTION DEPLOYMENT.
management:
  security:
    enabled: false

spring:
  ## Thymeleaf 3
  thymeleaf:
    decoupled-logic: true
